/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiHrActionRouteImport } from './routes/api/hr-action'
import { Route as ApiOpsRouteImport } from './routes/api/ops'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as AssistantIndexRouteImport } from './routes/assistant.index'
import { Route as AssistantSessionIdRouteImport } from './routes/assistant.$sessionId'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiEngineEmbedRouteImport } from './routes/api/engine/embed'
import { Route as ApiEngineSessionsRouteImport } from './routes/api/engine/sessions'
import { Route as ApiEngineTurnRouteImport } from './routes/api/engine/turn'
import { Route as ApiOpsEngineSessionsRouteImport } from './routes/api/ops/engine-sessions'
import { Route as OpsSessionsSessionIdRouteImport } from './routes/ops.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHrActionRoute = ApiHrActionRouteImport.update({
  id: '/api/hr-action',
  path: '/api/hr-action',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsRoute = ApiOpsRouteImport.update({
  id: '/api/ops',
  path: '/api/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantSessionIdRoute = AssistantSessionIdRouteImport.update({
  id: '/assistant/$sessionId',
  path: '/assistant/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEngineEmbedRoute = ApiEngineEmbedRouteImport.update({
  id: '/api/engine/embed',
  path: '/api/engine/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineSessionsRoute = ApiEngineSessionsRouteImport.update({
  id: '/api/engine/sessions',
  path: '/api/engine/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineTurnRoute = ApiEngineTurnRouteImport.update({
  id: '/api/engine/turn',
  path: '/api/engine/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsEngineSessionsRoute = ApiOpsEngineSessionsRouteImport.update({
  id: '/engine-sessions',
  path: '/engine-sessions',
  getParentRoute: () => ApiOpsRoute,
} as any)
const OpsSessionsSessionIdRoute = OpsSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => OpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/ops': typeof OpsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/hr-action': typeof ApiHrActionRoute
  '/api/ops': typeof ApiOpsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/engine/embed': typeof ApiEngineEmbedRoute
  '/api/engine/sessions': typeof ApiEngineSessionsRoute
  '/api/engine/turn': typeof ApiEngineTurnRoute
  '/api/ops/engine-sessions': typeof ApiOpsEngineSessionsRoute
  '/ops/sessions/$sessionId': typeof OpsSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/requests': typeof RequestsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/hr-action': typeof ApiHrActionRoute
  '/api/ops': typeof ApiOpsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/assistant': typeof AssistantIndexRoute
  '/ops': typeof OpsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/engine/embed': typeof ApiEngineEmbedRoute
  '/api/engine/sessions': typeof ApiEngineSessionsRoute
  '/api/engine/turn': typeof ApiEngineTurnRoute
  '/api/ops/engine-sessions': typeof ApiOpsEngineSessionsRoute
  '/ops/sessions/$sessionId': typeof OpsSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/ops': typeof OpsRouteWithChildren
  '/requests': typeof RequestsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/agent': typeof ApiAgentRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/api/hr-action': typeof ApiHrActionRoute
  '/api/ops': typeof ApiOpsRouteWithChildren
  '/api/session': typeof ApiSessionRoute
  '/assistant/$sessionId': typeof AssistantSessionIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/engine/embed': typeof ApiEngineEmbedRoute
  '/api/engine/sessions': typeof ApiEngineSessionsRoute
  '/api/engine/turn': typeof ApiEngineTurnRoute
  '/api/ops/engine-sessions': typeof ApiOpsEngineSessionsRoute
  '/ops/sessions/$sessionId': typeof OpsSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/ops'
    | '/requests'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/agent'
    | '/api/feedback'
    | '/api/hr-action'
    | '/api/ops'
    | '/api/session'
    | '/assistant/$sessionId'
    | '/assistant/'
    | '/ops/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/engine/embed'
    | '/api/engine/sessions'
    | '/api/engine/turn'
    | '/api/ops/engine-sessions'
    | '/ops/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/requests'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/agent'
    | '/api/feedback'
    | '/api/hr-action'
    | '/api/ops'
    | '/api/session'
    | '/assistant/$sessionId'
    | '/assistant'
    | '/ops'
    | '/.mcp/invoke-tool/$tool'
    | '/api/engine/embed'
    | '/api/engine/sessions'
    | '/api/engine/turn'
    | '/api/ops/engine-sessions'
    | '/ops/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/ops'
    | '/requests'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/agent'
    | '/api/feedback'
    | '/api/hr-action'
    | '/api/ops'
    | '/api/session'
    | '/assistant/$sessionId'
    | '/assistant/'
    | '/ops/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/engine/embed'
    | '/api/engine/sessions'
    | '/api/engine/turn'
    | '/api/ops/engine-sessions'
    | '/ops/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  OpsRoute: typeof OpsRouteWithChildren
  RequestsRoute: typeof RequestsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAgentRoute: typeof ApiAgentRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  ApiHrActionRoute: typeof ApiHrActionRoute
  ApiOpsRoute: typeof ApiOpsRouteWithChildren
  ApiSessionRoute: typeof ApiSessionRoute
  AssistantSessionIdRoute: typeof AssistantSessionIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiEngineEmbedRoute: typeof ApiEngineEmbedRoute
  ApiEngineSessionsRoute: typeof ApiEngineSessionsRoute
  ApiEngineTurnRoute: typeof ApiEngineTurnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hr-action': {
      id: '/api/hr-action'
      path: '/api/hr-action'
      fullPath: '/api/hr-action'
      preLoaderRoute: typeof ApiHrActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops': {
      id: '/api/ops'
      path: '/api/ops'
      fullPath: '/api/ops'
      preLoaderRoute: typeof ApiOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$sessionId': {
      id: '/assistant/$sessionId'
      path: '/assistant/$sessionId'
      fullPath: '/assistant/$sessionId'
      preLoaderRoute: typeof AssistantSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/embed': {
      id: '/api/engine/embed'
      path: '/api/engine/embed'
      fullPath: '/api/engine/embed'
      preLoaderRoute: typeof ApiEngineEmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/sessions': {
      id: '/api/engine/sessions'
      path: '/api/engine/sessions'
      fullPath: '/api/engine/sessions'
      preLoaderRoute: typeof ApiEngineSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/turn': {
      id: '/api/engine/turn'
      path: '/api/engine/turn'
      fullPath: '/api/engine/turn'
      preLoaderRoute: typeof ApiEngineTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/engine-sessions': {
      id: '/api/ops/engine-sessions'
      path: '/engine-sessions'
      fullPath: '/api/ops/engine-sessions'
      preLoaderRoute: typeof ApiOpsEngineSessionsRouteImport
      parentRoute: typeof ApiOpsRoute
    }
    '/ops/sessions/$sessionId': {
      id: '/ops/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/ops/sessions/$sessionId'
      preLoaderRoute: typeof OpsSessionsSessionIdRouteImport
      parentRoute: typeof OpsRoute
    }
  }
}

interface OpsRouteChildren {
  OpsIndexRoute: typeof OpsIndexRoute
  OpsSessionsSessionIdRoute: typeof OpsSessionsSessionIdRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsIndexRoute: OpsIndexRoute,
  OpsSessionsSessionIdRoute: OpsSessionsSessionIdRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface ApiOpsRouteChildren {
  ApiOpsEngineSessionsRoute: typeof ApiOpsEngineSessionsRoute
}

const ApiOpsRouteChildren: ApiOpsRouteChildren = {
  ApiOpsEngineSessionsRoute: ApiOpsEngineSessionsRoute,
}

const ApiOpsRouteWithChildren =
  ApiOpsRoute._addFileChildren(ApiOpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  OpsRoute: OpsRouteWithChildren,
  RequestsRoute: RequestsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAgentRoute: ApiAgentRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiHrActionRoute: ApiHrActionRoute,
  ApiOpsRoute: ApiOpsRouteWithChildren,
  ApiSessionRoute: ApiSessionRoute,
  AssistantSessionIdRoute: AssistantSessionIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiEngineEmbedRoute: ApiEngineEmbedRoute,
  ApiEngineSessionsRoute: ApiEngineSessionsRoute,
  ApiEngineTurnRoute: ApiEngineTurnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
